[colors]
background = '#252a36'
foreground = '#80E0A7'
cursor_bg = '#425563'
cursor_border = '#425563'
cursor_fg = '#252a36'

ansi = [
    '#0c0c0c',
    '#f65c4d',
    '#38b169',
    '#f6a728',
    '#36639b',
    '#d3427d',
    '#3b968c',
    '#b4b4b4',
]
brights = [
    '#425563',
    '#ff9287',
    '#aef158',
    '#ffde31',
    '#66c7f9',
    '#9c83f8',
    '#a3e9f1',
    '#ffffff',
]

[colors.tab_bar]
background = "#0c0c0c"

[colors.tab_bar.active_tab]
bg_color = '#252a36'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0c0c0c'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#0c0c0c'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'


[metadata]
name = 'SuperuserKAM'
origin_url = 'https://github.com/JSchmiegel/SuperuserKAM-TerminalTheme'